version: "3.8"

services:
  bootstrapper:
    build: .
    container_name: bootstrapper
    stop_grace_period: 0s
    ports:
      - "3000:3000"
    volumes:
      - /tmp/databases/:/tmp/databases/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NODE_ENV: production
    command: ["node", "dist/index.js"]
    restart: unless-stopped  # Ensures the container restarts if it crashes
    networks:
      - custom-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - custom-network

networks:
  custom-network:
    external: true
