version: "3.8"

services:
  bootstrapper:
    build: .
    container_name: bootstrapper
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NODE_ENV: production
    command: ["node", "dist/index.js"]
    restart: unless-stopped  # Ensures the container restarts if it crashes
